/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_JniTest */

#ifndef _Included_main_JniTest
#define _Included_main_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_JniTest
 * Method:    daemonRun
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_main_JniTest_daemonRun
        (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif


